# Generated by Django 4.1 on 2022-08-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_town'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='town',
        ),
    ]
