# Generated by Django 4.1 on 2022-08-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_user_extra_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='extra_field',
        ),
    ]
