# Generated by Django 4.1 on 2022-08-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='following',
            field=models.CharField(max_length=1000),
        ),
    ]
