# Generated by Django 4.1 on 2022-08-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_liked_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked_posts',
            name='liker',
            field=models.CharField(max_length=100),
        ),
    ]
